/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrder;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrderProduct;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryProduct;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryRestaurant;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryUser;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PK_ORDER = Indexes0.PK_ORDER;
    public static final Index PK_ORDER_PRODUCT = Indexes0.PK_ORDER_PRODUCT;
    public static final Index PK_PRODUCT = Indexes0.PK_PRODUCT;
    public static final Index PK_RESTAURANT = Indexes0.PK_RESTAURANT;
    public static final Index PK_USER = Indexes0.PK_USER;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PK_ORDER = Internal.createIndex("pk_order", DeliveryOrder.DELIVERY_ORDER, new OrderField[] { DeliveryOrder.DELIVERY_ORDER.ID_ORDER }, true);
        public static Index PK_ORDER_PRODUCT = Internal.createIndex("pk_order_product", DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT, new OrderField[] { DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT.ID_ORDER_PRODUCT }, true);
        public static Index PK_PRODUCT = Internal.createIndex("pk_product", DeliveryProduct.DELIVERY_PRODUCT, new OrderField[] { DeliveryProduct.DELIVERY_PRODUCT.ID_PRODUCT }, true);
        public static Index PK_RESTAURANT = Internal.createIndex("pk_restaurant", DeliveryRestaurant.DELIVERY_RESTAURANT, new OrderField[] { DeliveryRestaurant.DELIVERY_RESTAURANT.ID_RESTAURANT }, true);
        public static Index PK_USER = Internal.createIndex("pk_user", DeliveryUser.DELIVERY_USER, new OrderField[] { DeliveryUser.DELIVERY_USER.ID_USER }, true);
    }
}
