/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrder;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrderProduct;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryProduct;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryRestaurant;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryUser;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records.DeliveryOrderProductRecord;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records.DeliveryOrderRecord;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records.DeliveryProductRecord;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records.DeliveryRestaurantRecord;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records.DeliveryUserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DeliveryOrderRecord, Integer> IDENTITY_DELIVERY_ORDER = Identities0.IDENTITY_DELIVERY_ORDER;
    public static final Identity<DeliveryOrderProductRecord, Integer> IDENTITY_DELIVERY_ORDER_PRODUCT = Identities0.IDENTITY_DELIVERY_ORDER_PRODUCT;
    public static final Identity<DeliveryProductRecord, Integer> IDENTITY_DELIVERY_PRODUCT = Identities0.IDENTITY_DELIVERY_PRODUCT;
    public static final Identity<DeliveryRestaurantRecord, Integer> IDENTITY_DELIVERY_RESTAURANT = Identities0.IDENTITY_DELIVERY_RESTAURANT;
    public static final Identity<DeliveryUserRecord, Integer> IDENTITY_DELIVERY_USER = Identities0.IDENTITY_DELIVERY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DeliveryOrderRecord> PK_ORDER = UniqueKeys0.PK_ORDER;
    public static final UniqueKey<DeliveryOrderProductRecord> PK_ORDER_PRODUCT = UniqueKeys0.PK_ORDER_PRODUCT;
    public static final UniqueKey<DeliveryProductRecord> PK_PRODUCT = UniqueKeys0.PK_PRODUCT;
    public static final UniqueKey<DeliveryRestaurantRecord> PK_RESTAURANT = UniqueKeys0.PK_RESTAURANT;
    public static final UniqueKey<DeliveryUserRecord> PK_USER = UniqueKeys0.PK_USER;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DeliveryOrderRecord, DeliveryRestaurantRecord> DELIVERY_ORDER__FK_RESTAURANTE = ForeignKeys0.DELIVERY_ORDER__FK_RESTAURANTE;
    public static final ForeignKey<DeliveryOrderRecord, DeliveryUserRecord> DELIVERY_ORDER__FK_USER = ForeignKeys0.DELIVERY_ORDER__FK_USER;
    public static final ForeignKey<DeliveryOrderProductRecord, DeliveryOrderRecord> DELIVERY_ORDER_PRODUCT__FK_ORDER = ForeignKeys0.DELIVERY_ORDER_PRODUCT__FK_ORDER;
    public static final ForeignKey<DeliveryOrderProductRecord, DeliveryProductRecord> DELIVERY_ORDER_PRODUCT__FK_PRODUCT = ForeignKeys0.DELIVERY_ORDER_PRODUCT__FK_PRODUCT;
    public static final ForeignKey<DeliveryProductRecord, DeliveryRestaurantRecord> DELIVERY_PRODUCT__FK_RESTAURANTE = ForeignKeys0.DELIVERY_PRODUCT__FK_RESTAURANTE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DeliveryOrderRecord, Integer> IDENTITY_DELIVERY_ORDER = Internal.createIdentity(DeliveryOrder.DELIVERY_ORDER, DeliveryOrder.DELIVERY_ORDER.ID_ORDER);
        public static Identity<DeliveryOrderProductRecord, Integer> IDENTITY_DELIVERY_ORDER_PRODUCT = Internal.createIdentity(DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT, DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT.ID_ORDER_PRODUCT);
        public static Identity<DeliveryProductRecord, Integer> IDENTITY_DELIVERY_PRODUCT = Internal.createIdentity(DeliveryProduct.DELIVERY_PRODUCT, DeliveryProduct.DELIVERY_PRODUCT.ID_PRODUCT);
        public static Identity<DeliveryRestaurantRecord, Integer> IDENTITY_DELIVERY_RESTAURANT = Internal.createIdentity(DeliveryRestaurant.DELIVERY_RESTAURANT, DeliveryRestaurant.DELIVERY_RESTAURANT.ID_RESTAURANT);
        public static Identity<DeliveryUserRecord, Integer> IDENTITY_DELIVERY_USER = Internal.createIdentity(DeliveryUser.DELIVERY_USER, DeliveryUser.DELIVERY_USER.ID_USER);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DeliveryOrderRecord> PK_ORDER = Internal.createUniqueKey(DeliveryOrder.DELIVERY_ORDER, "pk_order", DeliveryOrder.DELIVERY_ORDER.ID_ORDER);
        public static final UniqueKey<DeliveryOrderProductRecord> PK_ORDER_PRODUCT = Internal.createUniqueKey(DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT, "pk_order_product", DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT.ID_ORDER_PRODUCT);
        public static final UniqueKey<DeliveryProductRecord> PK_PRODUCT = Internal.createUniqueKey(DeliveryProduct.DELIVERY_PRODUCT, "pk_product", DeliveryProduct.DELIVERY_PRODUCT.ID_PRODUCT);
        public static final UniqueKey<DeliveryRestaurantRecord> PK_RESTAURANT = Internal.createUniqueKey(DeliveryRestaurant.DELIVERY_RESTAURANT, "pk_restaurant", DeliveryRestaurant.DELIVERY_RESTAURANT.ID_RESTAURANT);
        public static final UniqueKey<DeliveryUserRecord> PK_USER = Internal.createUniqueKey(DeliveryUser.DELIVERY_USER, "pk_user", DeliveryUser.DELIVERY_USER.ID_USER);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<DeliveryOrderRecord, DeliveryRestaurantRecord> DELIVERY_ORDER__FK_RESTAURANTE = Internal.createForeignKey(br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Keys.PK_RESTAURANT, DeliveryOrder.DELIVERY_ORDER, "delivery_order__fk_restaurante", DeliveryOrder.DELIVERY_ORDER.ID_RESTAURANT);
        public static final ForeignKey<DeliveryOrderRecord, DeliveryUserRecord> DELIVERY_ORDER__FK_USER = Internal.createForeignKey(br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Keys.PK_USER, DeliveryOrder.DELIVERY_ORDER, "delivery_order__fk_user", DeliveryOrder.DELIVERY_ORDER.ID_USER);
        public static final ForeignKey<DeliveryOrderProductRecord, DeliveryOrderRecord> DELIVERY_ORDER_PRODUCT__FK_ORDER = Internal.createForeignKey(br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Keys.PK_ORDER, DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT, "delivery_order_product__fk_order", DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT.ID_ORDER);
        public static final ForeignKey<DeliveryOrderProductRecord, DeliveryProductRecord> DELIVERY_ORDER_PRODUCT__FK_PRODUCT = Internal.createForeignKey(br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Keys.PK_PRODUCT, DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT, "delivery_order_product__fk_product", DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT.ID_PRODUCT);
        public static final ForeignKey<DeliveryProductRecord, DeliveryRestaurantRecord> DELIVERY_PRODUCT__FK_RESTAURANTE = Internal.createForeignKey(br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Keys.PK_RESTAURANT, DeliveryProduct.DELIVERY_PRODUCT, "delivery_product__fk_restaurante", DeliveryProduct.DELIVERY_PRODUCT.ID_RESTAURANT);
    }
}
