/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrder;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrderProduct;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryProduct;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryRestaurant;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1498023252;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.delivery_order</code>.
     */
    public final DeliveryOrder DELIVERY_ORDER = br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrder.DELIVERY_ORDER;

    /**
     * The table <code>public.delivery_order_product</code>.
     */
    public final DeliveryOrderProduct DELIVERY_ORDER_PRODUCT = br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT;

    /**
     * The table <code>public.delivery_product</code>.
     */
    public final DeliveryProduct DELIVERY_PRODUCT = br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryProduct.DELIVERY_PRODUCT;

    /**
     * The table <code>public.delivery_restaurant</code>.
     */
    public final DeliveryRestaurant DELIVERY_RESTAURANT = br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryRestaurant.DELIVERY_RESTAURANT;

    /**
     * The table <code>public.delivery_user</code>.
     */
    public final DeliveryUser DELIVERY_USER = br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryUser.DELIVERY_USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.DELIVERY_ORDER_ID_ORDER_SEQ,
            Sequences.DELIVERY_ORDER_PRODUCT_ID_ORDER_PRODUCT_SEQ,
            Sequences.DELIVERY_PRODUCT_ID_PRODUCT_SEQ,
            Sequences.DELIVERY_RESTAURANT_ID_RESTAURANT_SEQ,
            Sequences.DELIVERY_USER_ID_USER_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            DeliveryOrder.DELIVERY_ORDER,
            DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT,
            DeliveryProduct.DELIVERY_PRODUCT,
            DeliveryRestaurant.DELIVERY_RESTAURANT,
            DeliveryUser.DELIVERY_USER);
    }
}
