/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.delivery_order_id_order_seq</code>
     */
    public static final Sequence<Long> DELIVERY_ORDER_ID_ORDER_SEQ = new SequenceImpl<Long>("delivery_order_id_order_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.delivery_order_product_id_order_product_seq</code>
     */
    public static final Sequence<Long> DELIVERY_ORDER_PRODUCT_ID_ORDER_PRODUCT_SEQ = new SequenceImpl<Long>("delivery_order_product_id_order_product_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.delivery_product_id_product_seq</code>
     */
    public static final Sequence<Long> DELIVERY_PRODUCT_ID_PRODUCT_SEQ = new SequenceImpl<Long>("delivery_product_id_product_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.delivery_restaurant_id_restaurant_seq</code>
     */
    public static final Sequence<Long> DELIVERY_RESTAURANT_ID_RESTAURANT_SEQ = new SequenceImpl<Long>("delivery_restaurant_id_restaurant_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.delivery_user_id_user_seq</code>
     */
    public static final Sequence<Long> DELIVERY_USER_ID_USER_SEQ = new SequenceImpl<Long>("delivery_user_id_user_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
