/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryOrderProduct;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryOrderProductRecord extends UpdatableRecordImpl<DeliveryOrderProductRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -22711548;

    /**
     * Setter for <code>public.delivery_order_product.id_order_product</code>.
     */
    public void setIdOrderProduct(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.delivery_order_product.id_order_product</code>.
     */
    public Integer getIdOrderProduct() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.delivery_order_product.id_order</code>.
     */
    public void setIdOrder(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.delivery_order_product.id_order</code>.
     */
    public Integer getIdOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.delivery_order_product.id_product</code>.
     */
    public void setIdProduct(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.delivery_order_product.id_product</code>.
     */
    public Integer getIdProduct() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT.ID_ORDER_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT.ID_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT.ID_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdOrderProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdOrderProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryOrderProductRecord value1(Integer value) {
        setIdOrderProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryOrderProductRecord value2(Integer value) {
        setIdOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryOrderProductRecord value3(Integer value) {
        setIdProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryOrderProductRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeliveryOrderProductRecord
     */
    public DeliveryOrderProductRecord() {
        super(DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT);
    }

    /**
     * Create a detached, initialised DeliveryOrderProductRecord
     */
    public DeliveryOrderProductRecord(Integer idOrderProduct, Integer idOrder, Integer idProduct) {
        super(DeliveryOrderProduct.DELIVERY_ORDER_PRODUCT);

        set(0, idOrderProduct);
        set(1, idOrder);
        set(2, idProduct);
    }
}
