/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryRestaurant;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryRestaurantRecord extends UpdatableRecordImpl<DeliveryRestaurantRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1817903810;

    /**
     * Setter for <code>public.delivery_restaurant.id_restaurant</code>.
     */
    public void setIdRestaurant(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.delivery_restaurant.id_restaurant</code>.
     */
    public Integer getIdRestaurant() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.delivery_restaurant.nm_restaurant</code>.
     */
    public void setNmRestaurant(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.delivery_restaurant.nm_restaurant</code>.
     */
    public String getNmRestaurant() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DeliveryRestaurant.DELIVERY_RESTAURANT.ID_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DeliveryRestaurant.DELIVERY_RESTAURANT.NM_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNmRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNmRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryRestaurantRecord value1(Integer value) {
        setIdRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryRestaurantRecord value2(String value) {
        setNmRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryRestaurantRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeliveryRestaurantRecord
     */
    public DeliveryRestaurantRecord() {
        super(DeliveryRestaurant.DELIVERY_RESTAURANT);
    }

    /**
     * Create a detached, initialised DeliveryRestaurantRecord
     */
    public DeliveryRestaurantRecord(Integer idRestaurant, String nmRestaurant) {
        super(DeliveryRestaurant.DELIVERY_RESTAURANT);

        set(0, idRestaurant);
        set(1, nmRestaurant);
    }
}
