/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.DeliveryUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryUserRecord extends UpdatableRecordImpl<DeliveryUserRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1398758794;

    /**
     * Setter for <code>public.delivery_user.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.delivery_user.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.delivery_user.nm_user</code>.
     */
    public void setNmUser(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.delivery_user.nm_user</code>.
     */
    public String getNmUser() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.delivery_user.login_user</code>.
     */
    public void setLoginUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.delivery_user.login_user</code>.
     */
    public String getLoginUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.delivery_user.pwd_user</code>.
     */
    public void setPwdUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.delivery_user.pwd_user</code>.
     */
    public String getPwdUser() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DeliveryUser.DELIVERY_USER.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DeliveryUser.DELIVERY_USER.NM_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DeliveryUser.DELIVERY_USER.LOGIN_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DeliveryUser.DELIVERY_USER.PWD_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNmUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLoginUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPwdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNmUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLoginUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPwdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryUserRecord value1(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryUserRecord value2(String value) {
        setNmUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryUserRecord value3(String value) {
        setLoginUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryUserRecord value4(String value) {
        setPwdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryUserRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeliveryUserRecord
     */
    public DeliveryUserRecord() {
        super(DeliveryUser.DELIVERY_USER);
    }

    /**
     * Create a detached, initialised DeliveryUserRecord
     */
    public DeliveryUserRecord(Integer idUser, String nmUser, String loginUser, String pwdUser) {
        super(DeliveryUser.DELIVERY_USER);

        set(0, idUser);
        set(1, nmUser);
        set(2, loginUser);
        set(3, pwdUser);
    }
}
