version: '3'

services:
  delivery_postgres:
    container_name: delivery_postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_ROOT_PASSWORD=delivery123
      - POSTGRES_DATABASE=delivery
      - POSTGRES_USER=delivery
      - POSTGRES_PASSWORD=delivery
    volumes:
      - "./init:/docker-entrypoint-initdb.d"

#sudo docker-compose -f docker-compose.yml up
