/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Indexes;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Keys;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Public;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records.DeliveryRestaurantRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryRestaurant extends TableImpl<DeliveryRestaurantRecord> {

    private static final long serialVersionUID = -152278598;

    /**
     * The reference instance of <code>public.delivery_restaurant</code>
     */
    public static final DeliveryRestaurant DELIVERY_RESTAURANT = new DeliveryRestaurant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeliveryRestaurantRecord> getRecordType() {
        return DeliveryRestaurantRecord.class;
    }

    /**
     * The column <code>public.delivery_restaurant.id_restaurant</code>.
     */
    public final TableField<DeliveryRestaurantRecord, Integer> ID_RESTAURANT = createField("id_restaurant", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('delivery_restaurant_id_restaurant_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.delivery_restaurant.nm_restaurant</code>.
     */
    public final TableField<DeliveryRestaurantRecord, String> NM_RESTAURANT = createField("nm_restaurant", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>public.delivery_restaurant</code> table reference
     */
    public DeliveryRestaurant() {
        this(DSL.name("delivery_restaurant"), null);
    }

    /**
     * Create an aliased <code>public.delivery_restaurant</code> table reference
     */
    public DeliveryRestaurant(String alias) {
        this(DSL.name(alias), DELIVERY_RESTAURANT);
    }

    /**
     * Create an aliased <code>public.delivery_restaurant</code> table reference
     */
    public DeliveryRestaurant(Name alias) {
        this(alias, DELIVERY_RESTAURANT);
    }

    private DeliveryRestaurant(Name alias, Table<DeliveryRestaurantRecord> aliased) {
        this(alias, aliased, null);
    }

    private DeliveryRestaurant(Name alias, Table<DeliveryRestaurantRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DeliveryRestaurant(Table<O> child, ForeignKey<O, DeliveryRestaurantRecord> key) {
        super(child, key, DELIVERY_RESTAURANT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_RESTAURANT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DeliveryRestaurantRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DELIVERY_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeliveryRestaurantRecord> getPrimaryKey() {
        return Keys.PK_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeliveryRestaurantRecord>> getKeys() {
        return Arrays.<UniqueKey<DeliveryRestaurantRecord>>asList(Keys.PK_RESTAURANT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryRestaurant as(String alias) {
        return new DeliveryRestaurant(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryRestaurant as(Name alias) {
        return new DeliveryRestaurant(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DeliveryRestaurant rename(String name) {
        return new DeliveryRestaurant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeliveryRestaurant rename(Name name) {
        return new DeliveryRestaurant(name, null);
    }
}
