/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Indexes;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Keys;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Public;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records.DeliveryOrderProductRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryOrderProduct extends TableImpl<DeliveryOrderProductRecord> {

    private static final long serialVersionUID = -803189259;

    /**
     * The reference instance of <code>public.delivery_order_product</code>
     */
    public static final DeliveryOrderProduct DELIVERY_ORDER_PRODUCT = new DeliveryOrderProduct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeliveryOrderProductRecord> getRecordType() {
        return DeliveryOrderProductRecord.class;
    }

    /**
     * The column <code>public.delivery_order_product.id_order_product</code>.
     */
    public final TableField<DeliveryOrderProductRecord, Integer> ID_ORDER_PRODUCT = createField("id_order_product", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('delivery_order_product_id_order_product_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.delivery_order_product.id_order</code>.
     */
    public final TableField<DeliveryOrderProductRecord, Integer> ID_ORDER = createField("id_order", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.delivery_order_product.id_product</code>.
     */
    public final TableField<DeliveryOrderProductRecord, Integer> ID_PRODUCT = createField("id_product", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.delivery_order_product</code> table reference
     */
    public DeliveryOrderProduct() {
        this(DSL.name("delivery_order_product"), null);
    }

    /**
     * Create an aliased <code>public.delivery_order_product</code> table reference
     */
    public DeliveryOrderProduct(String alias) {
        this(DSL.name(alias), DELIVERY_ORDER_PRODUCT);
    }

    /**
     * Create an aliased <code>public.delivery_order_product</code> table reference
     */
    public DeliveryOrderProduct(Name alias) {
        this(alias, DELIVERY_ORDER_PRODUCT);
    }

    private DeliveryOrderProduct(Name alias, Table<DeliveryOrderProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private DeliveryOrderProduct(Name alias, Table<DeliveryOrderProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DeliveryOrderProduct(Table<O> child, ForeignKey<O, DeliveryOrderProductRecord> key) {
        super(child, key, DELIVERY_ORDER_PRODUCT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_ORDER_PRODUCT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DeliveryOrderProductRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DELIVERY_ORDER_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeliveryOrderProductRecord> getPrimaryKey() {
        return Keys.PK_ORDER_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeliveryOrderProductRecord>> getKeys() {
        return Arrays.<UniqueKey<DeliveryOrderProductRecord>>asList(Keys.PK_ORDER_PRODUCT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DeliveryOrderProductRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DeliveryOrderProductRecord, ?>>asList(Keys.DELIVERY_ORDER_PRODUCT__FK_ORDER, Keys.DELIVERY_ORDER_PRODUCT__FK_PRODUCT);
    }

    public DeliveryOrder deliveryOrder() {
        return new DeliveryOrder(this, Keys.DELIVERY_ORDER_PRODUCT__FK_ORDER);
    }

    public DeliveryProduct deliveryProduct() {
        return new DeliveryProduct(this, Keys.DELIVERY_ORDER_PRODUCT__FK_PRODUCT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryOrderProduct as(String alias) {
        return new DeliveryOrderProduct(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryOrderProduct as(Name alias) {
        return new DeliveryOrderProduct(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DeliveryOrderProduct rename(String name) {
        return new DeliveryOrderProduct(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeliveryOrderProduct rename(Name name) {
        return new DeliveryOrderProduct(name, null);
    }
}
