/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables;


import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Indexes;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Keys;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.Public;
import br.com.mathidios.springboot.jooq.docker.postgres.model.jooq.tables.records.DeliveryUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryUser extends TableImpl<DeliveryUserRecord> {

    private static final long serialVersionUID = 1452266769;

    /**
     * The reference instance of <code>public.delivery_user</code>
     */
    public static final DeliveryUser DELIVERY_USER = new DeliveryUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeliveryUserRecord> getRecordType() {
        return DeliveryUserRecord.class;
    }

    /**
     * The column <code>public.delivery_user.id_user</code>.
     */
    public final TableField<DeliveryUserRecord, Integer> ID_USER = createField("id_user", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('delivery_user_id_user_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.delivery_user.nm_user</code>.
     */
    public final TableField<DeliveryUserRecord, String> NM_USER = createField("nm_user", org.jooq.impl.SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>public.delivery_user.login_user</code>.
     */
    public final TableField<DeliveryUserRecord, String> LOGIN_USER = createField("login_user", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.delivery_user.pwd_user</code>.
     */
    public final TableField<DeliveryUserRecord, String> PWD_USER = createField("pwd_user", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.delivery_user</code> table reference
     */
    public DeliveryUser() {
        this(DSL.name("delivery_user"), null);
    }

    /**
     * Create an aliased <code>public.delivery_user</code> table reference
     */
    public DeliveryUser(String alias) {
        this(DSL.name(alias), DELIVERY_USER);
    }

    /**
     * Create an aliased <code>public.delivery_user</code> table reference
     */
    public DeliveryUser(Name alias) {
        this(alias, DELIVERY_USER);
    }

    private DeliveryUser(Name alias, Table<DeliveryUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private DeliveryUser(Name alias, Table<DeliveryUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DeliveryUser(Table<O> child, ForeignKey<O, DeliveryUserRecord> key) {
        super(child, key, DELIVERY_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DeliveryUserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DELIVERY_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeliveryUserRecord> getPrimaryKey() {
        return Keys.PK_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeliveryUserRecord>> getKeys() {
        return Arrays.<UniqueKey<DeliveryUserRecord>>asList(Keys.PK_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryUser as(String alias) {
        return new DeliveryUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryUser as(Name alias) {
        return new DeliveryUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DeliveryUser rename(String name) {
        return new DeliveryUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeliveryUser rename(Name name) {
        return new DeliveryUser(name, null);
    }
}
